@ECHO OFF

SET CMAKE=cmake
SET CMAKE_DESTINATION="Build"
SET CMAKE_GENERATOR="Visual Studio 17 2022"

PUSHD %~dp0
MKDIR %CMAKE_DESTINATION% 2>NUL
PUSHD %CMAKE_DESTINATION%
%CMAKE% -A x64 -G %CMAKE_GENERATOR% "%~dp0"

pause